purification:
  total_num_iterations: 10
  csgm_num_iterations: 100
  purification_schedule: linear
  save_every_main: 100000
  save_every_sub: 100000
  optimizer: SGD
  lr: 1000
  momentum: 0.9
  ddim_num_iterations: 20
  full_ddim: True
  ddim_init_timestep: 400
  ddim_end_timestep: 0
  use_weight_decay: False
  weight_decay_lambda: 0
 

dataset:
  name: ffhq
  #img_size: !!python/tuple [1,3,256,256]
  root: ./data/ffhq

others:
  img_size: !!python/tuple [1,3,256,256]
